### ISSUE TITLE
Checklist contao widgets

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/contao-multicolumnwizard-bundle#25]
Checklist contao widgets:

- [x] Checkbox
- [ ] Checkbox with default - Error #29
- [x] Colorpicker
- [x] Filetree
- [x] Radio
- [x] Radio as table
- [x] Select
- [x] Select with Chosen
- [ ] Select with Chosen at second row (add with Ajax)
- [x] Pagetree
- [x] Text
- [x] Text + FilePicker
- [x] Text + PagePicker
- [x] Textarea
- [x] Textarea + TinyMCE

Options
- [x] DragAndDrop false
- [x] Min
- [x] Max
- [ ] Group
- [ ] Default
- [ ] Mandatory
- [ ] Unique
- [ ] Disabled/Readonly

Special
- [ ] MCW in MCW
- [ ] own template
- [ ] closures
